name: Build Docs
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-checks:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.found_paths.outputs.docs == 'true' || steps.should_force.outputs.should_force == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: found_paths
        uses: dorny/paths-filter@v3
        with:
          filters: |
            docs:
              - 'docs/**'
      - name: Determine if we should force the build
        id: should_force
        run: echo "should_force=${{ github.event_name == 'release' }}" >> "$GITHUB_OUTPUT"

  build:
    name: Build Docs
    needs: pre-checks
    if: ${{ needs.pre-checks.outputs.should_run == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Remove broken postcss.config.mjs
        run: rm -f /home/runner/work/AirTrail/AirTrail/postcss.config.mjs

      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build website
        run: bun run build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/
