name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: [ "Build Docs" ]
    types:
      - completed

jobs:
  pre-checks:
    runs-on: ubuntu-latest
    outputs:
      shouldDeploy: ${{ steps.should-deploy.outputs.deploy }}
    steps:
      - if: ${{ github.event.workflow_run.conclusion != 'success' }}
        run: echo 'The triggering workflow did not succeed' && exit 1
      - name: Should deploy
        id: should-deploy
        uses: actions/github-script@v7
        with:
          script: |
            const eventType = context.payload.workflow_run.event;
            const isFork = context.payload.workflow_run.repository.fork;
            core.setOutput("deploy", eventType === "release" && !isFork);

  deploy:
    name: Deploy to GitHub Pages
    needs: pre-checks
    if: ${{ needs.pre-checks.outputs.shouldDeploy }}

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4